server:
  port: 8769

eureka:
  instance:
    prefer-ip-address: true #让其他服务注册它也许能通过去改变去通过改变host的方式


spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/