spring:
  application:
    name: config-server2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YuanCoder/SpringcloudConfig/
          search-paths: respo
          username:  #your username
          password:  #your password
      label: master

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/


